[project]
name = "boardwyrm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "flask>=3.1.0",
    "python-lsp-server>=1.12.2",
]
